jenkins:
  systemMessage: "Company's Jarvis"
  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            assignments:
              - "authenticated"
        items:
          - name: "FolderA"
            description: "Jobs in Folder A, but not the folder itself"
            pattern: "A/.*"
            permissions:
              - "Job/Configure"
              - "Job/Build"
              - "Job/Delete"
            assignments:
              - "user1"
              - "user2"
          - name: "FolderB"
            description: "Jobs in Folder B, but not the folder itself"
            pattern: "B.*"
            permissions:
              - "Job/Configure"
              - "Job/Build"
            assignments:
              - "user2"
        agents:
          - name: "Agent1"
            description: "Agent 1"
            pattern: "agent1"
            permissions:
              - "Agent/Build"
            assignments:
              - "user1"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "adminp45s"
        - id: "user1"
          password: "user1p45s"
        - id: "user2"
          password: "user2p45s"
        - id: "user_hashed"
          # password is password
          password: "#jbcrypt:$2a$10$3bnAsorIxhl9kTYvNHa2hOJQwPzwT4bv9Vs.9KdXkh9ySANjJKm5u"

  crumbIssuer: "standard"
  remotingSecurity:
    enabled: true

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

unclassified:
  gitSCM:
    globalConfigEmail: "info@acep.web.id"
    globalConfigName: "Acep Saepudin"

tool:
  git:
    installations:
    - home: "git"
      name: "Default"

  maven:
    installations:
    - name: "Maven 3"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.5.4"
jobs:
  - script: >
      job('Seed job-dsl') {
        scm {
          git('https://github.com/acepsaepudin/jarvis-job-dsl.git')
        }
        steps {
          dsl {
            external('jobs/*.groovy')
            removeAction('DELETE')
          }
        }
      }

